name: kismet
favicon: null
layout_spectrum: 0.4598655088339001
typography_spectrum: 0.4292251127772033
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8635479714721441
  lightness: 0.7559856919106096
  saturation: 0.5830372653435916
  rhythmicContrast: 0.11396053689531982
purpose: []
